name: foodspan
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera:
  path_provider:
  path:
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  google_sign_in: ^6.0.2
  google_mlkit_text_recognition: ^0.5.0
  image_picker: 0.8.1
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.1
  google_fonts: ^2.1.1
  get_it: ^7.2.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/Group 39.png"
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
